#:schema node_modules/wrangler/config-schema.json
name = "synapse-ai-backend"
main = "dist/worker.js"
compatibility_date = "2025-09-08"
compatibility_flags = ["nodejs_compat"]

[build]
command = "bun run build"

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"

# Environment variables for staging
[env.staging.vars]
NODE_ENV = "staging"

# For local development
[env.development.vars]
NODE_ENV = "development"

# Database and external service configurations
# These will need to be set via `wrangler secret put` command
# - DATABASE_URL
# - SUPABASE_URL
# - SUPABASE_SERVICE_ROLE_KEY
# - SUPABASE_DB_URL
# - ANTHROPIC_API_KEY
# - OPENAI_API_KEY
